FROM python:3.9-slim 
WORKDIR /app 
COPY ../backend /app/backend 
COPY ../requirements.txt /app 
RUN pip install --no-cache-dir -r /app/requirements.txt 
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"] 
EXPOSE 8000 
